name: Go CI

on: [push]

jobs:
  lint:
    name: Run golangci-lint
    uses: golangci/golangci-lint-action@v3.4.0
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Run tests
      run: go test ./...
